export interface SkillCategory {
  name: string;
  skills: string[];
}

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    name: "Programming Languages",
    skills: [
      "JavaScript",
      "TypeScript",
      "Python",
      "Java",
      "C++",
      "C#",
      "Go",
      "Rust",
      "Ruby",
      "PHP",
      "Swift",
      "Kotlin",
      "Scala",
      "R",
      "MATLAB",
      "Dart",
    ],
  },
  {
    name: "Frontend Development",
    skills: [
      "React",
      "Next.js",
      "Vue.js",
      "Angular",
      "Svelte",
      "HTML",
      "CSS",
      "Tailwind CSS",
      "Bootstrap",
      "Sass",
      "Redux",
      "GraphQL Client",
      "Webpack",
      "Vite",
      "Storybook",
      "Framer Motion",
    ],
  },
  {
    name: "Backend Development",
    skills: [
      "Node.js",
      "Express.js",
      "Django",
      "Flask",
      "FastAPI",
      "Spring Boot",
      "Ruby on Rails",
      "ASP.NET",
      "NestJS",
      "GraphQL",
      "REST APIs",
      "gRPC",
      "WebSockets",
      "Microservices",
      "Serverless",
      "Hono",
    ],
  },
  {
    name: "Databases & Storage",
    skills: [
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "SQLite",
      "DynamoDB",
      "Supabase",
      "Firebase",
      "Prisma",
      "Drizzle ORM",
      "Elasticsearch",
      "Neo4j",
      "Cassandra",
      "SQL Server",
      "Oracle DB",
      "CockroachDB",
    ],
  },
  {
    name: "Cloud & DevOps",
    skills: [
      "AWS",
      "Google Cloud",
      "Azure",
      "Docker",
      "Kubernetes",
      "Terraform",
      "CI/CD",
      "GitHub Actions",
      "Jenkins",
      "Linux",
      "Nginx",
      "Vercel",
      "Netlify",
      "Cloudflare",
      "Ansible",
      "Helm",
    ],
  },
  {
    name: "Data Science & ML",
    skills: [
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "Jupyter",
      "Keras",
      "OpenCV",
      "NLP",
      "Computer Vision",
      "Deep Learning",
      "Data Visualization",
      "Spark",
      "Hadoop",
      "Tableau",
      "Power BI",
    ],
  },
  {
    name: "Mobile Development",
    skills: [
      "React Native",
      "Flutter",
      "SwiftUI",
      "Jetpack Compose",
      "Expo",
      "iOS Development",
      "Android Development",
      "Xamarin",
      "Ionic",
      "Capacitor",
      "App Store Deployment",
      "Push Notifications",
      "Mobile UI/UX",
      "ARKit",
      "Core ML",
      "Firebase Mobile",
    ],
  },
  {
    name: "Testing & QA",
    skills: [
      "Jest",
      "Cypress",
      "Playwright",
      "Selenium",
      "Vitest",
      "React Testing Library",
      "JUnit",
      "PyTest",
      "Mocha",
      "Unit Testing",
      "Integration Testing",
      "E2E Testing",
      "TDD",
      "Load Testing",
      "Postman",
      "K6",
    ],
  },
  {
    name: "Design & Creative",
    skills: [
      "Figma",
      "Adobe XD",
      "Sketch",
      "Photoshop",
      "Illustrator",
      "UI Design",
      "UX Research",
      "Wireframing",
      "Prototyping",
      "Design Systems",
      "Responsive Design",
      "Accessibility",
      "Color Theory",
      "Typography",
      "Motion Design",
      "Blender",
    ],
  },
  {
    name: "Tools & Collaboration",
    skills: [
      "Git",
      "GitHub",
      "GitLab",
      "Jira",
      "Confluence",
      "Notion",
      "Slack",
      "VS Code",
      "IntelliJ IDEA",
      "Agile/Scrum",
      "Technical Writing",
      "API Documentation",
      "Open Source",
      "Code Review",
      "Pair Programming",
      "System Design",
    ],
  },
];
